name: 🐛 Report a bug
description: Any errors.
labels: ["bug"]
body:
  - type: input
    attributes:
      label: Bug description
      description: A description of the 🐛 bug.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to reproduce the bug
      description: Provide steps to reproduce the 🐛 bug.
      placeholder: |
        Include steps to reproduce, the expected behaviour, and the actual behaviour.

        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false

  - type: textarea
    attributes:
      label: Error messages and logs
      description: >
        Provide any error messages and/or logs
      placeholder: "Copy the complete error messages and logs"
      value: |
        ```
        The error message you got, with the full traceback if available. Please paste it between these triple backticks.
        ```
    validations:
      required: false
