name: 🚀 Feature request
description: Propose a feature for this project
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Description & Motivation
      description: A clear and concise description of the 🚀 feature proposal
      placeholder: Write it here!